#ifndef _STITCH_TYPE_HPP_
#define _STITCH_TYPE_HPP_

enum StitchType {
  NONE_STITCH_TYPE,
  FACE_STITCH_TYPE,
  BACK_STITCH_TYPE,
  SAME_STITCH_TYPE,
  OPPOSITE_STITCH_TYPE
};

#endif // _STITCH_TYPE_HPP_